const serviceAreas = [
  "Naperville, IL",
  "Aurora, IL",
  "Joliet, IL",
  "Elgin, IL",
  "Waukegan, IL",
  "Cicero, IL",
  "Evanston, IL",
  "Schaumburg, IL",
  "Arlington Heights, IL",
  "Palatine, IL",
  "Skokie, IL",
  "Des Plaines, IL",
  "Orland Park, IL",
  "Oak Lawn, IL",
  "Berwyn, IL",
  "Mount Prospect, IL",
  "Tinley Park, IL",
  "Oak Park, IL",
  "Wheaton, IL",
  "Downers Grove, IL",
  "Elmhurst, IL",
  "Glenview, IL",
  "Buffalo Grove, IL",
  "Northbrook, IL",
  "Deerfield, IL",
  "Highland Park, IL",
  "Libertyville, IL",
  "Vernon Hills, IL",
  "Hoffman Estates, IL",
  "Bolingbrook, IL",
  "Plainfield, IL",
  "St. Charles, IL",
  "Geneva, IL",
  "Batavia, IL",
  "Addison, IL",
  "Lombard, IL",
  "Carol Stream, IL",
  "Streamwood, IL",
  "Hanover Park, IL",
  "Roselle, IL",
  "Park Ridge, IL",
  "Niles, IL",
  "Morton Grove, IL",
  "Bensenville, IL",
  "La Grange, IL",
  "Hinsdale, IL",
  "Burr Ridge, IL",
  "Western Springs, IL",
];

export { serviceAreas };
